# Generated by Django 3.2.6 on 2021-11-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
