# Generated by Django 3.2.6 on 2021-11-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='company_id',
            new_name='company',
        ),
    ]
